import React from 'react'
import Content from '../../components/content'
import Meaning from '../../components/meaning'

export default () => (
  <Meaning previous={{title:"Financial statement", link: "/financial-statement"}} title="Income tax">
    <Content>
      An income tax is a tax that governments impose on income generated by businesses and individuals within their jurisdiction. By law, taxpayers must file an income tax return annually to determine their tax obligations. Income taxes are a source of revenue for governments. They are used to fund public services, pay government obligations, and provide goods for citizens.
    </Content>
  </Meaning>
)